# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ee745357da7e1e4354320aef496eb0ce96097e76de6de6a3ebf79b98e876d839b9013b48931f0b3852ff1f7c150cf4a6f87e62bd4a4311cf7cfc55cc86a1d4

test:
  secret_key_base: 00dddec0b2fd2d4297e0f4d1b425ff4ce98ed05dd29aea5b7c07c9b33307c40c41cecc47774b5d4a4a46d3966008eaca3f4f62f085281ee19cb35ef7ee7b7c3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
